# Generated by Django 5.2.5 on 2026-04-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=254)),
                ('consulta', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('respondido', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('url', models.URLField()),
                ('imagen', models.ImageField(upload_to='proyectos/')),
                ('icono', models.CharField(default='🌐', help_text='Emoji o ícono para la tarjeta', max_length=50)),
                ('tecnologias', models.CharField(help_text='Ej: React, Node.js, MongoDB', max_length=300)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
    ]
